src/java/jpa/entities/Locations.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Gibson Levvid
 */
@Entity
@Table(name = "Locations")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Locations.findAll", query = "SELECT l FROM Locations l"),
    @NamedQuery(name = "Locations.findByLocationID", query = "SELECT l FROM Locations l WHERE l.locationID = :locationID"),
    @NamedQuery(name = "Locations.findByBuilding", query = "SELECT l FROM Locations l WHERE l.building = :building"),
    @NamedQuery(name = "Locations.findByLocDescription", query = "SELECT l FROM Locations l WHERE l.locDescription = :locDescription"),
    @NamedQuery(name = "Locations.findByContactGroup", query = "SELECT l FROM Locations l WHERE l.contactGroup = :contactGroup"),
    @NamedQuery(name = "Locations.findByPhoneNr", query = "SELECT l FROM Locations l WHERE l.phoneNr = :phoneNr")})
public class Locations implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "LocationID")
    private String locationID;
    @Size(max = 50)
    @Column(name = "Building")
    private String building;
    @Size(max = 50)
    @Column(name = "Loc_Description")
    private String locDescription;
    @Size(max = 20)
    @Column(name = "ContactGroup")
    private String contactGroup;
    @Size(max = 12)
    @Column(name = "PhoneNr")
    private String phoneNr;

    public Locations() {
    }

    public Locations(String locationID) {
        this.locationID = locationID;
    }

    public String getLocationID() {
        return locationID;
    }

    public void setLocationID(String locationID) {
        this.locationID = locationID;
    }

    public String getBuilding() {
        return building;
    }

    public void setBuilding(String building) {
        this.building = building;
    }

    public String getLocDescription() {
        return locDescription;
    }

    public void setLocDescription(String locDescription) {
        this.locDescription = locDescription;
    }

    public String getContactGroup() {
        return contactGroup;
    }

    public void setContactGroup(String contactGroup) {
        this.contactGroup = contactGroup;
    }

    public String getPhoneNr() {
        return phoneNr;
    }

    public void setPhoneNr(String phoneNr) {
        this.phoneNr = phoneNr;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (locationID != null ? locationID.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Locations)) {
            return false;
        }
        Locations other = (Locations) object;
        if ((this.locationID == null && other.locationID != null) || (this.locationID != null && !this.locationID.equals(other.locationID))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Locations[ locationID=" + locationID + " ]";
    }
    
}

src/java/jsf/LocationsController.java
package jsf;

import jpa.entities.Locations;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.LocationsFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Named("locationsController")
@SessionScoped
public class LocationsController implements Serializable {

    private Locations current;
    private DataModel items = null;
    @EJB
    private jpa.session.LocationsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public LocationsController() {
    }

    public Locations getSelected() {
        if (current == null) {
            current = new Locations();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LocationsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(30) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Locations) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }
    

    public String prepareCreate() {
        current = new Locations();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LocationsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Locations) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LocationsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Locations) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LocationsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Locations getLocations(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Locations.class)
    public static class LocationsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LocationsController controller = (LocationsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "locationsController");
            return controller.getLocations(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Locations) {
                Locations o = (Locations) object;
                return getStringKey(o.getLocationID());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Locations.class.getName());
            }
        }

    }
    
    
    /*********************Additional code to enable search and better page navigation*************/
    private int search = 0;
    private int first=0;
    private int last=0;
    private int listLength = 0;
    List tableDataList;
    @PersistenceContext
    private EntityManager entityManager;
    
    /********************************Pagination*********************************/
    public String backToTable(){
        recreateModel();
        getItems();
        first =0;
        search = 0;
        return "List";
    } 
    
     public String nextSearchItems(){
        first = first+30;
        
        if(last+30>listLength()){
            last = listLength();
        }
        else{
            last = last+30;
        }
        items.setWrappedData(tableDataList.subList(first, last-1));
        return "List";
    }
    
    public String previousSearchItems(){
        first = first-30;
        last = last- 30;
        items.setWrappedData(tableDataList.subList(first, last-1));
        return "List";
    }
    
    /*********************************Search************************************/
    /*Helper methods*/
    public int search(){
        return search;
    }
    
    public int first(){
        return first;
    }
     
     
    public int last(){
        return last;
    }
     
    public int listLength(){
         return listLength;
    }
    
    public boolean searchHasPrevious(){
        return first>29;
    }
    
    public boolean searchHasNext(){
        return last<listLength();
    }
    
    /*Returns true when s is a string, false when it is a number*/
     public boolean isString(String s){
         try{
            Integer.parseInt(s);
            return false;
         }
         catch(NumberFormatException e){
             return true;
         }
     }
     
     
     /**Helper methods**/
      public String analyseSearchString(String field, String input, String type){
        String search = "", parameter=" AND";
        
        String[] longerSearch = input.trim().split(" ");
        if(longerSearch.length>1&&((input.trim().indexOf("\"")!=0)||
                (input.trim().indexOf("\"")!=input.length()-1))){
            for(int i=0; i<longerSearch.length;i++){
                if(i==longerSearch.length-1){
                    search +=" i." + field+ " LIKE " + "'%" + longerSearch[i] +"%' " + type; 
                }
                else{
                    search +=" i." + field + " LIKE " + "'%" + longerSearch[i] +"%' " + parameter;
                }
            }
        }
        else{
            search += " i." + field + " LIKE " + "'%" + input +"%' " + type;

web/locations/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateLocationsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateLocationsLabel_locationID}" for="locationID" />
                    <h:inputText id="locationID" value="#{locationsController.selected.locationID}" title="#{bundle.CreateLocationsTitle_locationID}" required="true" requiredMessage="#{bundle.CreateLocationsRequiredMessage_locationID}"/>
                    <h:outputLabel value="#{bundle.CreateLocationsLabel_building}" for="building" />
                    <h:inputText id="building" value="#{locationsController.selected.building}" title="#{bundle.CreateLocationsTitle_building}" />
                    <h:outputLabel value="#{bundle.CreateLocationsLabel_locDescription}" for="locDescription" />
                    <h:inputText id="locDescription" value="#{locationsController.selected.locDescription}" title="#{bundle.CreateLocationsTitle_locDescription}" />
                    <h:outputLabel value="#{bundle.CreateLocationsLabel_contactGroup}" for="contactGroup" />
                    <h:inputText id="contactGroup" value="#{locationsController.selected.contactGroup}" title="#{bundle.CreateLocationsTitle_contactGroup}" />
                    <h:outputLabel value="#{bundle.CreateLocationsLabel_phoneNr}" for="phoneNr" />
                    <h:inputText id="phoneNr" value="#{locationsController.selected.phoneNr}" title="#{bundle.CreateLocationsTitle_phoneNr}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{locationsController.create}" value="#{bundle.CreateLocationsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{locationsController.prepareList}" value="#{bundle.CreateLocationsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateLocationsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/locations/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditLocationsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditLocationsLabel_locationID}" for="locationID" />
                    <h:inputText id="locationID" value="#{locationsController.selected.locationID}" title="#{bundle.EditLocationsTitle_locationID}" required="true" requiredMessage="#{bundle.EditLocationsRequiredMessage_locationID}"/>
                    <h:outputLabel value="#{bundle.EditLocationsLabel_building}" for="building" />
                    <h:inputText id="building" value="#{locationsController.selected.building}" title="#{bundle.EditLocationsTitle_building}" />
                    <h:outputLabel value="#{bundle.EditLocationsLabel_locDescription}" for="locDescription" />
                    <h:inputText id="locDescription" value="#{locationsController.selected.locDescription}" title="#{bundle.EditLocationsTitle_locDescription}" />
                    <h:outputLabel value="#{bundle.EditLocationsLabel_contactGroup}" for="contactGroup" />
                    <h:inputText id="contactGroup" value="#{locationsController.selected.contactGroup}" title="#{bundle.EditLocationsTitle_contactGroup}" />
                    <h:outputLabel value="#{bundle.EditLocationsLabel_phoneNr}" for="phoneNr" />
                    <h:inputText id="phoneNr" value="#{locationsController.selected.phoneNr}" title="#{bundle.EditLocationsTitle_phoneNr}" />
                </h:panelGrid>
                <h:commandLink action="#{locationsController.update}" value="#{bundle.EditLocationsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditLocationsViewLink}"/>
                <br />
                <h:commandLink action="#{locationsController.prepareList}" value="#{bundle.EditLocationsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditLocationsIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/locations/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListLocationsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                    
                <!--Beginning of additional code-->
                <!--When no items are found-->
                <h:panelGroup rendered="#{locationsController.items.rowCount == 0}">
                    <h:outputText escape="false" value="#{bundle.ListLocationsEmpty}"/>
                    <h:commandLink action="#{locationsController.backToTable()}" 
                               value="Locations"/>&nbsp;
                    <h:link outcome="/index" value="#{bundle.ListLocationsIndexLink}" />&nbsp; 
                </h:panelGroup>
                
                
               
                <h:panelGroup rendered="#{locationsController.items.rowCount > 0}">
                    <h:panelGroup rendered="#{ locationsController.search()==0}">
                        <h:outputText value="#{locationsController.pagination.pageFirstItem + 1}
                                      ..#{locationsController.pagination.pageLastItem + 1}/
                                      #{locationsController.pagination.itemsCount}"/>&nbsp;
                        <h:commandLink action="#{locationsController.previous}" 
                                       value="#{bundle.Previous} #{locationsController.pagination.pageSize}" 
                                       rendered="#{locationsController.pagination.hasPreviousPage}"/>&nbsp;
                        <h:commandLink action="#{locationsController.next}" 
                                       value="#{bundle.Next} #{locationsController.pagination.pageSize}" 
                                       rendered="#{locationsController.pagination.hasNextPage}"/>&nbsp; 
                    </h:panelGroup>
                    
                    
                    
                    <!--Search next previous etc-->
                    <h:panelGroup rendered="#{ locationsController.search()==1}">
                        <h:outputText value="#{locationsController.first()+ 1}..
                                      #{locationsController.last()}/
                                      #{locationsController.listLength()}"/>&nbsp;
                        <h:commandLink action="#{locationsController.previousSearchItems()}" 
                                       value="#{bundle.Previous} #{locationsController.pagination.pageSize}" 
                                       rendered="#{locationsController.searchHasPrevious()}"/>&nbsp;
                        <h:commandLink action="#{locationsController.nextSearchItems()}" 
                                       value="#{bundle.Next} #{locationsController.pagination.pageSize}" 
                                       rendered="#{locationsController.searchHasNext()}"/>&nbsp; 
                    </h:panelGroup>
                    <h:commandLink action="#{locationsController.prepareCreate}" 
                                   value="#{bundle.ListLocationsCreateLink}" 
                                   rendered="#{locationsController.isAdmin() == true}"/>&nbsp; 
           
                                 &nbsp; 
                    <h:commandLink action="#{locationsController.backToTable()}" 
                                   value="Locations" />&nbsp; 
                    <h:link outcome="/index" value="#{bundle.ListLocationsIndexLink}" />&nbsp;
                    
                
                <br></br>
                <!--SEARCH-->
                
                <br>
                    <h:inputText value="#{locationid}" size="15" p:placeholder="Location ID" 
                                 styleClass="search"/> &nbsp;
                    
                    <h:inputText value="#{building}" size="15" p:placeholder="Building" 
                                 styleClass="search"/>&nbsp;&nbsp;
                    <h:inputText value="#{locdescription}" size="15" p:placeholder="Locdescription" 
                                 styleClass="search"/>&nbsp;
                    <h:inputText value="#{contactgroup}" size="15" p:placeholder="Contact Group" 
                                 styleClass="search"/>&nbsp;
                    <h:inputText value="#{phonenr}" size="15" p:placeholder="Phone Number" 
                                 styleClass="search"/>&nbsp;
                    
                    
                    <h:commandButton value="Search" 
                                     action="#{locationsController.basicSearch(
                                               locationid, building, locdescription, 
                                               contactgroup, phonenr)}"  
                                               styleClass="searchButton"/> 
                </br>
                
                <!--End of additional code-->
                
                
                
                    
                
                    <h:dataTable value="#{locationsController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocationsTitle_locationID}"/>
                            </f:facet>
                            <h:outputText value="#{item.locationID}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocationsTitle_building}"/>
                            </f:facet>
                            <h:outputText value="#{item.building}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocationsTitle_locDescription}"/>
                            </f:facet>
                            <h:outputText value="#{item.locDescription}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocationsTitle_contactGroup}"/>
                            </f:facet>
                            <h:outputText value="#{item.contactGroup}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocationsTitle_phoneNr}"/>
                            </f:facet>
                            <h:outputText value="#{item.phoneNr}"/>
                        </h:column>
                        <h:column rendered="#{locationsController.isAdmin() == true}">
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{locationsController.prepareView}" value="#{bundle.ListLocationsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{locationsController.prepareEdit}" value="#{bundle.ListLocationsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{locationsController.destroy}" value="#{bundle.ListLocationsDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/locations/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewLocationsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewLocationsLabel_locationID}"/>
                    <h:outputText value="#{locationsController.selected.locationID}" title="#{bundle.ViewLocationsTitle_locationID}"/>
                    <h:outputText value="#{bundle.ViewLocationsLabel_building}"/>
                    <h:outputText value="#{locationsController.selected.building}" title="#{bundle.ViewLocationsTitle_building}"/>
                    <h:outputText value="#{bundle.ViewLocationsLabel_locDescription}"/>
                    <h:outputText value="#{locationsController.selected.locDescription}" title="#{bundle.ViewLocationsTitle_locDescription}"/>
                    <h:outputText value="#{bundle.ViewLocationsLabel_contactGroup}"/>
                    <h:outputText value="#{locationsController.selected.contactGroup}" title="#{bundle.ViewLocationsTitle_contactGroup}"/>
                    <h:outputText value="#{bundle.ViewLocationsLabel_phoneNr}"/>
                    <h:outputText value="#{locationsController.selected.phoneNr}" title="#{bundle.ViewLocationsTitle_phoneNr}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{locationsController.destroyAndView}" value="#{bundle.ViewLocationsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewLocationsEditLink}"/>
                <br />
                <h:commandLink action="#{locationsController.prepareCreate}" value="#{bundle.ViewLocationsCreateLink}" />
                <br />
                <h:commandLink action="#{locationsController.prepareList}" value="#{bundle.ViewLocationsShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewLocationsIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>